<?xml version="1.0" encoding="utf-8"?><Database Name="NotificationManagement" Class="NotificationManagementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.2.182;Initial Catalog=NotificationManagement;Persist Security Info=True;User ID=sa" SettingsObjectName="AutoSendCapNhapDH.Properties.Settings" SettingsPropertyName="NotificationManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Template_AutomaticMail" Member="Template_AutomaticMails">
    <Type Name="Template_AutomaticMail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodeTemplate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="EmailTo" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="EmailCC" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="EmailBCC" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Data" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="Email_SmtpClient_Template_AutomaticMail" Member="Email_SmtpClient" ThisKey="Source" OtherKey="SourceID" Type="Email_SmtpClient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Email_SmtpClient" Member="Email_SmtpClients">
    <Type Name="Email_SmtpClient">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SourceID" Type="System.String" DbType="VarChar(500) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pass" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Host" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Port" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Email_SmtpClient_Template_AutomaticMail" Member="Template_AutomaticMails" ThisKey="SourceID" OtherKey="Source" Type="Template_AutomaticMail" />
    </Type>
  </Table>
</Database>