#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSendCapNhapDH.NETSUITETT
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NetsuiteTT")]
	public partial class NETSUITETTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_Mapping_Mavattu_DVT(Table_Mapping_Mavattu_DVT instance);
    partial void UpdateTable_Mapping_Mavattu_DVT(Table_Mapping_Mavattu_DVT instance);
    partial void DeleteTable_Mapping_Mavattu_DVT(Table_Mapping_Mavattu_DVT instance);
    partial void InsertKho(Kho instance);
    partial void UpdateKho(Kho instance);
    partial void DeleteKho(Kho instance);
    partial void InsertKhoVai(KhoVai instance);
    partial void UpdateKhoVai(KhoVai instance);
    partial void DeleteKhoVai(KhoVai instance);
    partial void InsertLoaiSanPham(LoaiSanPham instance);
    partial void UpdateLoaiSanPham(LoaiSanPham instance);
    partial void DeleteLoaiSanPham(LoaiSanPham instance);
    #endregion
		
		public NETSUITETTDataContext() : 
				base(global::AutoSendCapNhapDH.Properties.Settings.Default.NetsuiteTTConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public NETSUITETTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NETSUITETTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NETSUITETTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NETSUITETTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_Mapping_Mavattu_DVT> Table_Mapping_Mavattu_DVTs
		{
			get
			{
				return this.GetTable<Table_Mapping_Mavattu_DVT>();
			}
		}
		
		public System.Data.Linq.Table<Kho> Khos
		{
			get
			{
				return this.GetTable<Kho>();
			}
		}
		
		public System.Data.Linq.Table<KhoVai> KhoVais
		{
			get
			{
				return this.GetTable<KhoVai>();
			}
		}
		
		public System.Data.Linq.Table<LoaiSanPham> LoaiSanPhams
		{
			get
			{
				return this.GetTable<LoaiSanPham>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_mapping_netsuite_gioitinh_sex")]
		public ISingleResult<sp_mapping_netsuite_gioitinh_sexResult> sp_mapping_netsuite_gioitinh_sex([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string code_sex)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code_sex);
			return ((ISingleResult<sp_mapping_netsuite_gioitinh_sexResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_mapping_loaispct")]
		public ISingleResult<sp_mapping_loaispctResult> sp_mapping_loaispct([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string kytu1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maloaispct)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kytu1, maloaispct);
			return ((ISingleResult<sp_mapping_loaispctResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Mapping_Mavattu_DVT")]
	public partial class Table_Mapping_Mavattu_DVT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Internalid;
		
		private string _Externalid;
		
		private string _DVT;
		
		private string _TenDVT;
		
		private int _stt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInternalidChanging(string value);
    partial void OnInternalidChanged();
    partial void OnExternalidChanging(string value);
    partial void OnExternalidChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnTenDVTChanging(string value);
    partial void OnTenDVTChanged();
    partial void OnsttChanging(int value);
    partial void OnsttChanged();
    #endregion
		
		public Table_Mapping_Mavattu_DVT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Internalid", DbType="VarChar(50)")]
		public string Internalid
		{
			get
			{
				return this._Internalid;
			}
			set
			{
				if ((this._Internalid != value))
				{
					this.OnInternalidChanging(value);
					this.SendPropertyChanging();
					this._Internalid = value;
					this.SendPropertyChanged("Internalid");
					this.OnInternalidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Externalid", DbType="VarChar(50)")]
		public string Externalid
		{
			get
			{
				return this._Externalid;
			}
			set
			{
				if ((this._Externalid != value))
				{
					this.OnExternalidChanging(value);
					this.SendPropertyChanging();
					this._Externalid = value;
					this.SendPropertyChanged("Externalid");
					this.OnExternalidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="VarChar(50)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDVT", DbType="NVarChar(50)")]
		public string TenDVT
		{
			get
			{
				return this._TenDVT;
			}
			set
			{
				if ((this._TenDVT != value))
				{
					this.OnTenDVTChanging(value);
					this.SendPropertyChanging();
					this._TenDVT = value;
					this.SendPropertyChanged("TenDVT");
					this.OnTenDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stt", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int stt
		{
			get
			{
				return this._stt;
			}
			set
			{
				if ((this._stt != value))
				{
					this.OnsttChanging(value);
					this.SendPropertyChanging();
					this._stt = value;
					this.SendPropertyChanged("stt");
					this.OnsttChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kho")]
	public partial class Kho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private string _externalid;
		
		private string _name;
		
		private string _parent;
		
		private string _makho;
		
		private string _tenkho;
		
		private string _loai;
		
		private string _ID_nhamaysx;
		
		private string _IDMADV;
		
		private string _NHAMAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnexternalidChanging(string value);
    partial void OnexternalidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnparentChanging(string value);
    partial void OnparentChanged();
    partial void OnmakhoChanging(string value);
    partial void OnmakhoChanged();
    partial void OntenkhoChanging(string value);
    partial void OntenkhoChanged();
    partial void OnloaiChanging(string value);
    partial void OnloaiChanged();
    partial void OnID_nhamaysxChanging(string value);
    partial void OnID_nhamaysxChanged();
    partial void OnIDMADVChanging(string value);
    partial void OnIDMADVChanged();
    partial void OnNHAMAYChanging(string value);
    partial void OnNHAMAYChanged();
    #endregion
		
		public Kho()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externalid", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string externalid
		{
			get
			{
				return this._externalid;
			}
			set
			{
				if ((this._externalid != value))
				{
					this.OnexternalidChanging(value);
					this.SendPropertyChanging();
					this._externalid = value;
					this.SendPropertyChanged("externalid");
					this.OnexternalidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(200)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent", DbType="VarChar(100)")]
		public string parent
		{
			get
			{
				return this._parent;
			}
			set
			{
				if ((this._parent != value))
				{
					this.OnparentChanging(value);
					this.SendPropertyChanging();
					this._parent = value;
					this.SendPropertyChanged("parent");
					this.OnparentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makho", DbType="VarChar(100)")]
		public string makho
		{
			get
			{
				return this._makho;
			}
			set
			{
				if ((this._makho != value))
				{
					this.OnmakhoChanging(value);
					this.SendPropertyChanging();
					this._makho = value;
					this.SendPropertyChanged("makho");
					this.OnmakhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkho", DbType="NVarChar(200)")]
		public string tenkho
		{
			get
			{
				return this._tenkho;
			}
			set
			{
				if ((this._tenkho != value))
				{
					this.OntenkhoChanging(value);
					this.SendPropertyChanging();
					this._tenkho = value;
					this.SendPropertyChanged("tenkho");
					this.OntenkhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai", DbType="VarChar(50)")]
		public string loai
		{
			get
			{
				return this._loai;
			}
			set
			{
				if ((this._loai != value))
				{
					this.OnloaiChanging(value);
					this.SendPropertyChanging();
					this._loai = value;
					this.SendPropertyChanged("loai");
					this.OnloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_nhamaysx", DbType="VarChar(50)")]
		public string ID_nhamaysx
		{
			get
			{
				return this._ID_nhamaysx;
			}
			set
			{
				if ((this._ID_nhamaysx != value))
				{
					this.OnID_nhamaysxChanging(value);
					this.SendPropertyChanging();
					this._ID_nhamaysx = value;
					this.SendPropertyChanged("ID_nhamaysx");
					this.OnID_nhamaysxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMADV", DbType="VarChar(50)")]
		public string IDMADV
		{
			get
			{
				return this._IDMADV;
			}
			set
			{
				if ((this._IDMADV != value))
				{
					this.OnIDMADVChanging(value);
					this.SendPropertyChanging();
					this._IDMADV = value;
					this.SendPropertyChanged("IDMADV");
					this.OnIDMADVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHAMAY", DbType="VarChar(50)")]
		public string NHAMAY
		{
			get
			{
				return this._NHAMAY;
			}
			set
			{
				if ((this._NHAMAY != value))
				{
					this.OnNHAMAYChanging(value);
					this.SendPropertyChanging();
					this._NHAMAY = value;
					this.SendPropertyChanged("NHAMAY");
					this.OnNHAMAYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhoVai")]
	public partial class KhoVai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Externalid;
		
		private string _Name;
		
		private string _MaKhoVai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExternalidChanging(string value);
    partial void OnExternalidChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnMaKhoVaiChanging(string value);
    partial void OnMaKhoVaiChanged();
    #endregion
		
		public KhoVai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Externalid", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Externalid
		{
			get
			{
				return this._Externalid;
			}
			set
			{
				if ((this._Externalid != value))
				{
					this.OnExternalidChanging(value);
					this.SendPropertyChanging();
					this._Externalid = value;
					this.SendPropertyChanged("Externalid");
					this.OnExternalidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoVai", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhoVai
		{
			get
			{
				return this._MaKhoVai;
			}
			set
			{
				if ((this._MaKhoVai != value))
				{
					this.OnMaKhoVaiChanging(value);
					this.SendPropertyChanging();
					this._MaKhoVai = value;
					this.SendPropertyChanged("MaKhoVai");
					this.OnMaKhoVaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiSanPham")]
	public partial class LoaiSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _externalid;
		
		private string _name;
		
		private string _LoaiSanPham1;
		
		private string _KyTu1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnexternalidChanging(string value);
    partial void OnexternalidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnLoaiSanPham1Changing(string value);
    partial void OnLoaiSanPham1Changed();
    partial void OnKyTu1Changing(string value);
    partial void OnKyTu1Changed();
    #endregion
		
		public LoaiSanPham()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externalid", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string externalid
		{
			get
			{
				return this._externalid;
			}
			set
			{
				if ((this._externalid != value))
				{
					this.OnexternalidChanging(value);
					this.SendPropertyChanging();
					this._externalid = value;
					this.SendPropertyChanged("externalid");
					this.OnexternalidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(150)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="LoaiSanPham", Storage="_LoaiSanPham1", DbType="VarChar(100)")]
		public string LoaiSanPham1
		{
			get
			{
				return this._LoaiSanPham1;
			}
			set
			{
				if ((this._LoaiSanPham1 != value))
				{
					this.OnLoaiSanPham1Changing(value);
					this.SendPropertyChanging();
					this._LoaiSanPham1 = value;
					this.SendPropertyChanged("LoaiSanPham1");
					this.OnLoaiSanPham1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KyTu1", DbType="VarChar(50)")]
		public string KyTu1
		{
			get
			{
				return this._KyTu1;
			}
			set
			{
				if ((this._KyTu1 != value))
				{
					this.OnKyTu1Changing(value);
					this.SendPropertyChanging();
					this._KyTu1 = value;
					this.SendPropertyChanged("KyTu1");
					this.OnKyTu1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_mapping_netsuite_gioitinh_sexResult
	{
		
		private string _code_sex;
		
		private string _decription;
		
		private string _internalID;
		
		public sp_mapping_netsuite_gioitinh_sexResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_sex", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string code_sex
		{
			get
			{
				return this._code_sex;
			}
			set
			{
				if ((this._code_sex != value))
				{
					this._code_sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decription", DbType="NVarChar(50)")]
		public string decription
		{
			get
			{
				return this._decription;
			}
			set
			{
				if ((this._decription != value))
				{
					this._decription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_internalID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string internalID
		{
			get
			{
				return this._internalID;
			}
			set
			{
				if ((this._internalID != value))
				{
					this._internalID = value;
				}
			}
		}
	}
	
	public partial class sp_mapping_loaispctResult
	{
		
		private string _externalid;
		
		private string _Name;
		
		private string _MaLoaiSPCT;
		
		private string _PhanNhomSanPham;
		
		private string _Kytu1;
		
		private string _MoTa;
		
		public sp_mapping_loaispctResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externalid", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string externalid
		{
			get
			{
				return this._externalid;
			}
			set
			{
				if ((this._externalid != value))
				{
					this._externalid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiSPCT", DbType="VarChar(150)")]
		public string MaLoaiSPCT
		{
			get
			{
				return this._MaLoaiSPCT;
			}
			set
			{
				if ((this._MaLoaiSPCT != value))
				{
					this._MaLoaiSPCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanNhomSanPham", DbType="NVarChar(150)")]
		public string PhanNhomSanPham
		{
			get
			{
				return this._PhanNhomSanPham;
			}
			set
			{
				if ((this._PhanNhomSanPham != value))
				{
					this._PhanNhomSanPham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kytu1", DbType="VarChar(50)")]
		public string Kytu1
		{
			get
			{
				return this._Kytu1;
			}
			set
			{
				if ((this._Kytu1 != value))
				{
					this._Kytu1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(500)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this._MoTa = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
