#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSendCapNhapDH.QLSANPHAMMAY2023
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLSANPHAMMAY2023")]
	public partial class QLSANPHAMMAY2023DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDMLOAISP(DMLOAISP instance);
    partial void UpdateDMLOAISP(DMLOAISP instance);
    partial void DeleteDMLOAISP(DMLOAISP instance);
    partial void InsertDMMAHANG(DMMAHANG instance);
    partial void UpdateDMMAHANG(DMMAHANG instance);
    partial void DeleteDMMAHANG(DMMAHANG instance);
    #endregion
		
		public QLSANPHAMMAY2023DataContext() : 
				base(global::AutoSendCapNhapDH.Properties.Settings.Default.QLSANPHAMMAY2023ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QLSANPHAMMAY2023DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSANPHAMMAY2023DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSANPHAMMAY2023DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSANPHAMMAY2023DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DMLOAISP> DMLOAISPs
		{
			get
			{
				return this.GetTable<DMLOAISP>();
			}
		}
		
		public System.Data.Linq.Table<DMMAHANG> DMMAHANGs
		{
			get
			{
				return this.GetTable<DMMAHANG>();
			}
		}
		
		public System.Data.Linq.Table<DMSIZE> DMSIZEs
		{
			get
			{
				return this.GetTable<DMSIZE>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_load_NetsuiteTT_Table_Mapping_MaHangSPM_MaKieuDang")]
		public ISingleResult<sp_load_NetsuiteTT_Table_Mapping_MaHangSPM_MaKieuDangResult> sp_load_NetsuiteTT_Table_Mapping_MaHangSPM_MaKieuDang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maloaisp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string loaisp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maloaisp, loaisp);
			return ((ISingleResult<sp_load_NetsuiteTT_Table_Mapping_MaHangSPM_MaKieuDangResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_load_Tbl_Mapping_NguonGocSP_ThuongHieu")]
		public ISingleResult<sp_load_Tbl_Mapping_NguonGocSP_ThuongHieuResult> sp_load_Tbl_Mapping_NguonGocSP_ThuongHieu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nguongoc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nguongoc);
			return ((ISingleResult<sp_load_Tbl_Mapping_NguonGocSP_ThuongHieuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_mapping_nhamaysx_location")]
		public ISingleResult<sp_mapping_nhamaysx_locationResult> sp_mapping_nhamaysx_location([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nhamay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nhamay);
			return ((ISingleResult<sp_mapping_nhamaysx_locationResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_mapping_DanhMucLoaiKhachHang_PHANLOAIKHACHHANG")]
		public ISingleResult<sp_mapping_DanhMucLoaiKhachHang_PHANLOAIKHACHHANGResult> sp_mapping_DanhMucLoaiKhachHang_PHANLOAIKHACHHANG([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string loaikh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), loaikh);
			return ((ISingleResult<sp_mapping_DanhMucLoaiKhachHang_PHANLOAIKHACHHANGResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_mapping_Donvidathang_Department")]
		public ISingleResult<sp_mapping_Donvidathang_DepartmentResult> sp_mapping_Donvidathang_Department([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string donvidathang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), donvidathang);
			return ((ISingleResult<sp_mapping_Donvidathang_DepartmentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_mapping_Donvidathang_Department_byidmacs")]
		public ISingleResult<sp_mapping_Donvidathang_Department_byidmacsResult> sp_mapping_Donvidathang_Department_byidmacs([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string idmacs)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idmacs);
			return ((ISingleResult<sp_mapping_Donvidathang_Department_byidmacsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_mapping_NetsuiteTT_TenHopQui")]
		public ISingleResult<sp_mapping_NetsuiteTT_TenHopQuiResult> sp_mapping_NetsuiteTT_TenHopQui([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string kytudau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nhomsp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kytudau, nhomsp);
			return ((ISingleResult<sp_mapping_NetsuiteTT_TenHopQuiResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.api_erp_daymahang_SPM")]
		public ISingleResult<api_erp_daymahang_SPMResult> api_erp_daymahang_SPM([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string manv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manv);
			return ((ISingleResult<api_erp_daymahang_SPMResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DMLOAISP")]
	public partial class DMLOAISP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LOAISP;
		
		private string _TENLOAI;
		
		private System.Nullable<bool> _HIEULUC;
		
		private string _Kytu1;
		
		private EntitySet<DMMAHANG> _DMMAHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLOAISPChanging(string value);
    partial void OnLOAISPChanged();
    partial void OnTENLOAIChanging(string value);
    partial void OnTENLOAIChanged();
    partial void OnHIEULUCChanging(System.Nullable<bool> value);
    partial void OnHIEULUCChanged();
    partial void OnKytu1Changing(string value);
    partial void OnKytu1Changed();
    #endregion
		
		public DMLOAISP()
		{
			this._DMMAHANGs = new EntitySet<DMMAHANG>(new Action<DMMAHANG>(this.attach_DMMAHANGs), new Action<DMMAHANG>(this.detach_DMMAHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAISP", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LOAISP
		{
			get
			{
				return this._LOAISP;
			}
			set
			{
				if ((this._LOAISP != value))
				{
					this.OnLOAISPChanging(value);
					this.SendPropertyChanging();
					this._LOAISP = value;
					this.SendPropertyChanged("LOAISP");
					this.OnLOAISPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI", DbType="NVarChar(200)")]
		public string TENLOAI
		{
			get
			{
				return this._TENLOAI;
			}
			set
			{
				if ((this._TENLOAI != value))
				{
					this.OnTENLOAIChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI = value;
					this.SendPropertyChanged("TENLOAI");
					this.OnTENLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIEULUC", DbType="Bit")]
		public System.Nullable<bool> HIEULUC
		{
			get
			{
				return this._HIEULUC;
			}
			set
			{
				if ((this._HIEULUC != value))
				{
					this.OnHIEULUCChanging(value);
					this.SendPropertyChanging();
					this._HIEULUC = value;
					this.SendPropertyChanged("HIEULUC");
					this.OnHIEULUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kytu1", DbType="VarChar(1)")]
		public string Kytu1
		{
			get
			{
				return this._Kytu1;
			}
			set
			{
				if ((this._Kytu1 != value))
				{
					this.OnKytu1Changing(value);
					this.SendPropertyChanging();
					this._Kytu1 = value;
					this.SendPropertyChanged("Kytu1");
					this.OnKytu1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DMLOAISP_DMMAHANG", Storage="_DMMAHANGs", ThisKey="LOAISP", OtherKey="LOAISP")]
		public EntitySet<DMMAHANG> DMMAHANGs
		{
			get
			{
				return this._DMMAHANGs;
			}
			set
			{
				this._DMMAHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DMMAHANGs(DMMAHANG entity)
		{
			this.SendPropertyChanging();
			entity.DMLOAISP = this;
		}
		
		private void detach_DMMAHANGs(DMMAHANG entity)
		{
			this.SendPropertyChanging();
			entity.DMLOAISP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DMMAHANG")]
	public partial class DMMAHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAMH;
		
		private string _mahangketoan;
		
		private string _MAHANG_TINHGIA;
		
		private string _TENMH;
		
		private string _NHOMHANG;
		
		private string _Donvidathang;
		
		private string _MAU;
		
		private string _Nhamaysx;
		
		private string _SIZE;
		
		private string _Mahangnhapkhau;
		
		private string _BONG;
		
		private string _GHICHU;
		
		private string _MANV;
		
		private System.Nullable<System.DateTime> _NGAYNHAP;
		
		private System.Nullable<bool> _HIEULUC;
		
		private string _LOAISP;
		
		private string _TENHOPQUI;
		
		private string _MANVGC;
		
		private System.Nullable<bool> _GuiAPI;
		
		private System.Nullable<System.DateTime> _NgayGuiAPI;
		
		private string _HINHANH;
		
		private string _Barcode;
		
		private string _qrcode;
		
		private EntityRef<DMLOAISP> _DMLOAISP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAMHChanging(string value);
    partial void OnMAMHChanged();
    partial void OnmahangketoanChanging(string value);
    partial void OnmahangketoanChanged();
    partial void OnMAHANG_TINHGIAChanging(string value);
    partial void OnMAHANG_TINHGIAChanged();
    partial void OnTENMHChanging(string value);
    partial void OnTENMHChanged();
    partial void OnNHOMHANGChanging(string value);
    partial void OnNHOMHANGChanged();
    partial void OnDonvidathangChanging(string value);
    partial void OnDonvidathangChanged();
    partial void OnMAUChanging(string value);
    partial void OnMAUChanged();
    partial void OnNhamaysxChanging(string value);
    partial void OnNhamaysxChanged();
    partial void OnSIZEChanging(string value);
    partial void OnSIZEChanged();
    partial void OnMahangnhapkhauChanging(string value);
    partial void OnMahangnhapkhauChanged();
    partial void OnBONGChanging(string value);
    partial void OnBONGChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnNGAYNHAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYNHAPChanged();
    partial void OnHIEULUCChanging(System.Nullable<bool> value);
    partial void OnHIEULUCChanged();
    partial void OnLOAISPChanging(string value);
    partial void OnLOAISPChanged();
    partial void OnTENHOPQUIChanging(string value);
    partial void OnTENHOPQUIChanged();
    partial void OnMANVGCChanging(string value);
    partial void OnMANVGCChanged();
    partial void OnGuiAPIChanging(System.Nullable<bool> value);
    partial void OnGuiAPIChanged();
    partial void OnNgayGuiAPIChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGuiAPIChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnBarcodeChanging(string value);
    partial void OnBarcodeChanged();
    partial void OnqrcodeChanging(string value);
    partial void OnqrcodeChanged();
    #endregion
		
		public DMMAHANG()
		{
			this._DMLOAISP = default(EntityRef<DMLOAISP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMH", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAMH
		{
			get
			{
				return this._MAMH;
			}
			set
			{
				if ((this._MAMH != value))
				{
					this.OnMAMHChanging(value);
					this.SendPropertyChanging();
					this._MAMH = value;
					this.SendPropertyChanged("MAMH");
					this.OnMAMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahangketoan", DbType="VarChar(50)")]
		public string mahangketoan
		{
			get
			{
				return this._mahangketoan;
			}
			set
			{
				if ((this._mahangketoan != value))
				{
					this.OnmahangketoanChanging(value);
					this.SendPropertyChanging();
					this._mahangketoan = value;
					this.SendPropertyChanged("mahangketoan");
					this.OnmahangketoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHANG_TINHGIA", DbType="VarChar(50)")]
		public string MAHANG_TINHGIA
		{
			get
			{
				return this._MAHANG_TINHGIA;
			}
			set
			{
				if ((this._MAHANG_TINHGIA != value))
				{
					this.OnMAHANG_TINHGIAChanging(value);
					this.SendPropertyChanging();
					this._MAHANG_TINHGIA = value;
					this.SendPropertyChanged("MAHANG_TINHGIA");
					this.OnMAHANG_TINHGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENMH", DbType="NVarChar(200)")]
		public string TENMH
		{
			get
			{
				return this._TENMH;
			}
			set
			{
				if ((this._TENMH != value))
				{
					this.OnTENMHChanging(value);
					this.SendPropertyChanging();
					this._TENMH = value;
					this.SendPropertyChanged("TENMH");
					this.OnTENMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHOMHANG", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NHOMHANG
		{
			get
			{
				return this._NHOMHANG;
			}
			set
			{
				if ((this._NHOMHANG != value))
				{
					this.OnNHOMHANGChanging(value);
					this.SendPropertyChanging();
					this._NHOMHANG = value;
					this.SendPropertyChanged("NHOMHANG");
					this.OnNHOMHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Donvidathang", DbType="VarChar(1)")]
		public string Donvidathang
		{
			get
			{
				return this._Donvidathang;
			}
			set
			{
				if ((this._Donvidathang != value))
				{
					this.OnDonvidathangChanging(value);
					this.SendPropertyChanging();
					this._Donvidathang = value;
					this.SendPropertyChanged("Donvidathang");
					this.OnDonvidathangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAU", DbType="VarChar(3)")]
		public string MAU
		{
			get
			{
				return this._MAU;
			}
			set
			{
				if ((this._MAU != value))
				{
					this.OnMAUChanging(value);
					this.SendPropertyChanging();
					this._MAU = value;
					this.SendPropertyChanged("MAU");
					this.OnMAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhamaysx", DbType="VarChar(1)")]
		public string Nhamaysx
		{
			get
			{
				return this._Nhamaysx;
			}
			set
			{
				if ((this._Nhamaysx != value))
				{
					this.OnNhamaysxChanging(value);
					this.SendPropertyChanging();
					this._Nhamaysx = value;
					this.SendPropertyChanged("Nhamaysx");
					this.OnNhamaysxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIZE", DbType="VarChar(50)")]
		public string SIZE
		{
			get
			{
				return this._SIZE;
			}
			set
			{
				if ((this._SIZE != value))
				{
					this.OnSIZEChanging(value);
					this.SendPropertyChanging();
					this._SIZE = value;
					this.SendPropertyChanged("SIZE");
					this.OnSIZEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahangnhapkhau", DbType="VarChar(50)")]
		public string Mahangnhapkhau
		{
			get
			{
				return this._Mahangnhapkhau;
			}
			set
			{
				if ((this._Mahangnhapkhau != value))
				{
					this.OnMahangnhapkhauChanging(value);
					this.SendPropertyChanging();
					this._Mahangnhapkhau = value;
					this.SendPropertyChanged("Mahangnhapkhau");
					this.OnMahangnhapkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BONG", DbType="VarChar(50)")]
		public string BONG
		{
			get
			{
				return this._BONG;
			}
			set
			{
				if ((this._BONG != value))
				{
					this.OnBONGChanging(value);
					this.SendPropertyChanging();
					this._BONG = value;
					this.SendPropertyChanged("BONG");
					this.OnBONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(200)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(50)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNHAP", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYNHAP
		{
			get
			{
				return this._NGAYNHAP;
			}
			set
			{
				if ((this._NGAYNHAP != value))
				{
					this.OnNGAYNHAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYNHAP = value;
					this.SendPropertyChanged("NGAYNHAP");
					this.OnNGAYNHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIEULUC", DbType="Bit")]
		public System.Nullable<bool> HIEULUC
		{
			get
			{
				return this._HIEULUC;
			}
			set
			{
				if ((this._HIEULUC != value))
				{
					this.OnHIEULUCChanging(value);
					this.SendPropertyChanging();
					this._HIEULUC = value;
					this.SendPropertyChanged("HIEULUC");
					this.OnHIEULUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAISP", DbType="VarChar(50)")]
		public string LOAISP
		{
			get
			{
				return this._LOAISP;
			}
			set
			{
				if ((this._LOAISP != value))
				{
					if (this._DMLOAISP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLOAISPChanging(value);
					this.SendPropertyChanging();
					this._LOAISP = value;
					this.SendPropertyChanged("LOAISP");
					this.OnLOAISPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHOPQUI", DbType="NVarChar(MAX)")]
		public string TENHOPQUI
		{
			get
			{
				return this._TENHOPQUI;
			}
			set
			{
				if ((this._TENHOPQUI != value))
				{
					this.OnTENHOPQUIChanging(value);
					this.SendPropertyChanging();
					this._TENHOPQUI = value;
					this.SendPropertyChanged("TENHOPQUI");
					this.OnTENHOPQUIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANVGC", DbType="VarChar(50)")]
		public string MANVGC
		{
			get
			{
				return this._MANVGC;
			}
			set
			{
				if ((this._MANVGC != value))
				{
					this.OnMANVGCChanging(value);
					this.SendPropertyChanging();
					this._MANVGC = value;
					this.SendPropertyChanged("MANVGC");
					this.OnMANVGCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuiAPI", DbType="Bit")]
		public System.Nullable<bool> GuiAPI
		{
			get
			{
				return this._GuiAPI;
			}
			set
			{
				if ((this._GuiAPI != value))
				{
					this.OnGuiAPIChanging(value);
					this.SendPropertyChanging();
					this._GuiAPI = value;
					this.SendPropertyChanged("GuiAPI");
					this.OnGuiAPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGuiAPI", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGuiAPI
		{
			get
			{
				return this._NgayGuiAPI;
			}
			set
			{
				if ((this._NgayGuiAPI != value))
				{
					this.OnNgayGuiAPIChanging(value);
					this.SendPropertyChanging();
					this._NgayGuiAPI = value;
					this.SendPropertyChanged("NgayGuiAPI");
					this.OnNgayGuiAPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="VarChar(MAX)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="VarChar(MAX)")]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this.OnBarcodeChanging(value);
					this.SendPropertyChanging();
					this._Barcode = value;
					this.SendPropertyChanged("Barcode");
					this.OnBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qrcode", DbType="VarChar(MAX)")]
		public string qrcode
		{
			get
			{
				return this._qrcode;
			}
			set
			{
				if ((this._qrcode != value))
				{
					this.OnqrcodeChanging(value);
					this.SendPropertyChanging();
					this._qrcode = value;
					this.SendPropertyChanged("qrcode");
					this.OnqrcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DMLOAISP_DMMAHANG", Storage="_DMLOAISP", ThisKey="LOAISP", OtherKey="LOAISP", IsForeignKey=true)]
		public DMLOAISP DMLOAISP
		{
			get
			{
				return this._DMLOAISP.Entity;
			}
			set
			{
				DMLOAISP previousValue = this._DMLOAISP.Entity;
				if (((previousValue != value) 
							|| (this._DMLOAISP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DMLOAISP.Entity = null;
						previousValue.DMMAHANGs.Remove(this);
					}
					this._DMLOAISP.Entity = value;
					if ((value != null))
					{
						value.DMMAHANGs.Add(this);
						this._LOAISP = value.LOAISP;
					}
					else
					{
						this._LOAISP = default(string);
					}
					this.SendPropertyChanged("DMLOAISP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DMSIZE")]
	public partial class DMSIZE
	{
		
		private string _SIZE;
		
		private string _KYTU15;
		
		private string _KYTU11;
		
		private string _TenSIZE;
		
		private string _GHICHU;
		
		private System.Nullable<bool> _HIEULUC;
		
		private System.Nullable<int> _STT;
		
		private string _Externalid;
		
		public DMSIZE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIZE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SIZE
		{
			get
			{
				return this._SIZE;
			}
			set
			{
				if ((this._SIZE != value))
				{
					this._SIZE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KYTU15", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string KYTU15
		{
			get
			{
				return this._KYTU15;
			}
			set
			{
				if ((this._KYTU15 != value))
				{
					this._KYTU15 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KYTU11", DbType="VarChar(1)")]
		public string KYTU11
		{
			get
			{
				return this._KYTU11;
			}
			set
			{
				if ((this._KYTU11 != value))
				{
					this._KYTU11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSIZE", DbType="NVarChar(200)")]
		public string TenSIZE
		{
			get
			{
				return this._TenSIZE;
			}
			set
			{
				if ((this._TenSIZE != value))
				{
					this._TenSIZE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(200)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this._GHICHU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIEULUC", DbType="Bit")]
		public System.Nullable<bool> HIEULUC
		{
			get
			{
				return this._HIEULUC;
			}
			set
			{
				if ((this._HIEULUC != value))
				{
					this._HIEULUC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int")]
		public System.Nullable<int> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Externalid", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Externalid
		{
			get
			{
				return this._Externalid;
			}
			set
			{
				if ((this._Externalid != value))
				{
					this._Externalid = value;
				}
			}
		}
	}
	
	public partial class sp_load_NetsuiteTT_Table_Mapping_MaHangSPM_MaKieuDangResult
	{
		
		private string _Externalid_MaKieuDang;
		
		private string _ID_TT;
		
		private string _Name;
		
		private string _LOAISP;
		
		private string _Externalid_NhomMDSD;
		
		private string _Externalid_LoaiSPMay;
		
		public sp_load_NetsuiteTT_Table_Mapping_MaHangSPM_MaKieuDangResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Externalid_MaKieuDang", DbType="VarChar(50)")]
		public string Externalid_MaKieuDang
		{
			get
			{
				return this._Externalid_MaKieuDang;
			}
			set
			{
				if ((this._Externalid_MaKieuDang != value))
				{
					this._Externalid_MaKieuDang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ID_TT
		{
			get
			{
				return this._ID_TT;
			}
			set
			{
				if ((this._ID_TT != value))
				{
					this._ID_TT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAISP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LOAISP
		{
			get
			{
				return this._LOAISP;
			}
			set
			{
				if ((this._LOAISP != value))
				{
					this._LOAISP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Externalid_NhomMDSD", DbType="VarChar(50)")]
		public string Externalid_NhomMDSD
		{
			get
			{
				return this._Externalid_NhomMDSD;
			}
			set
			{
				if ((this._Externalid_NhomMDSD != value))
				{
					this._Externalid_NhomMDSD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Externalid_LoaiSPMay", DbType="VarChar(50)")]
		public string Externalid_LoaiSPMay
		{
			get
			{
				return this._Externalid_LoaiSPMay;
			}
			set
			{
				if ((this._Externalid_LoaiSPMay != value))
				{
					this._Externalid_LoaiSPMay = value;
				}
			}
		}
	}
	
	public partial class sp_load_Tbl_Mapping_NguonGocSP_ThuongHieuResult
	{
		
		private string _Externalid;
		
		private string _ID_TT;
		
		private string _Name;
		
		private string _Internalid;
		
		public sp_load_Tbl_Mapping_NguonGocSP_ThuongHieuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Externalid", DbType="VarChar(50)")]
		public string Externalid
		{
			get
			{
				return this._Externalid;
			}
			set
			{
				if ((this._Externalid != value))
				{
					this._Externalid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TT", DbType="NChar(10)")]
		public string ID_TT
		{
			get
			{
				return this._ID_TT;
			}
			set
			{
				if ((this._ID_TT != value))
				{
					this._ID_TT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Internalid", DbType="VarChar(50)")]
		public string Internalid
		{
			get
			{
				return this._Internalid;
			}
			set
			{
				if ((this._Internalid != value))
				{
					this._Internalid = value;
				}
			}
		}
	}
	
	public partial class sp_mapping_nhamaysx_locationResult
	{
		
		private int _STT;
		
		private string _externalid;
		
		private string _name;
		
		private string _parent;
		
		private string _makho;
		
		private string _tenkho;
		
		private string _loai;
		
		private string _ID_nhamaysx;
		
		public sp_mapping_nhamaysx_locationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int NOT NULL")]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externalid", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string externalid
		{
			get
			{
				return this._externalid;
			}
			set
			{
				if ((this._externalid != value))
				{
					this._externalid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(200)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent", DbType="VarChar(100)")]
		public string parent
		{
			get
			{
				return this._parent;
			}
			set
			{
				if ((this._parent != value))
				{
					this._parent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makho", DbType="VarChar(100)")]
		public string makho
		{
			get
			{
				return this._makho;
			}
			set
			{
				if ((this._makho != value))
				{
					this._makho = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkho", DbType="NVarChar(200)")]
		public string tenkho
		{
			get
			{
				return this._tenkho;
			}
			set
			{
				if ((this._tenkho != value))
				{
					this._tenkho = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai", DbType="VarChar(50)")]
		public string loai
		{
			get
			{
				return this._loai;
			}
			set
			{
				if ((this._loai != value))
				{
					this._loai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_nhamaysx", DbType="VarChar(50)")]
		public string ID_nhamaysx
		{
			get
			{
				return this._ID_nhamaysx;
			}
			set
			{
				if ((this._ID_nhamaysx != value))
				{
					this._ID_nhamaysx = value;
				}
			}
		}
	}
	
	public partial class sp_mapping_DanhMucLoaiKhachHang_PHANLOAIKHACHHANGResult
	{
		
		private string _LoaiKhachHang;
		
		private string _KhachHang;
		
		private System.Nullable<bool> _HieuLuc;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private string _LastModifiedByID;
		
		private System.Nullable<System.DateTime> _LastModifiedDate;
		
		private string _internalid_phanloaikh;
		
		public sp_mapping_DanhMucLoaiKhachHang_PHANLOAIKHACHHANGResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKhachHang", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiKhachHang
		{
			get
			{
				return this._LoaiKhachHang;
			}
			set
			{
				if ((this._LoaiKhachHang != value))
				{
					this._LoaiKhachHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhachHang", DbType="NVarChar(500)")]
		public string KhachHang
		{
			get
			{
				return this._KhachHang;
			}
			set
			{
				if ((this._KhachHang != value))
				{
					this._KhachHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HieuLuc", DbType="Bit")]
		public System.Nullable<bool> HieuLuc
		{
			get
			{
				return this._HieuLuc;
			}
			set
			{
				if ((this._HieuLuc != value))
				{
					this._HieuLuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(250)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedByID", DbType="NVarChar(250)")]
		public string LastModifiedByID
		{
			get
			{
				return this._LastModifiedByID;
			}
			set
			{
				if ((this._LastModifiedByID != value))
				{
					this._LastModifiedByID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifiedDate
		{
			get
			{
				return this._LastModifiedDate;
			}
			set
			{
				if ((this._LastModifiedDate != value))
				{
					this._LastModifiedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_internalid_phanloaikh", DbType="VarChar(50)")]
		public string internalid_phanloaikh
		{
			get
			{
				return this._internalid_phanloaikh;
			}
			set
			{
				if ((this._internalid_phanloaikh != value))
				{
					this._internalid_phanloaikh = value;
				}
			}
		}
	}
	
	public partial class sp_mapping_Donvidathang_DepartmentResult
	{
		
		private string _internalid;
		
		private string _externalid;
		
		private string _name;
		
		private string _parent;
		
		private string _idmadv;
		
		private string _madv;
		
		private string _idmacs;
		
		private string _mabp;
		
		private string _donvidathang;
		
		public sp_mapping_Donvidathang_DepartmentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_internalid", DbType="VarChar(50)")]
		public string internalid
		{
			get
			{
				return this._internalid;
			}
			set
			{
				if ((this._internalid != value))
				{
					this._internalid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externalid", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string externalid
		{
			get
			{
				return this._externalid;
			}
			set
			{
				if ((this._externalid != value))
				{
					this._externalid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent", DbType="VarChar(50)")]
		public string parent
		{
			get
			{
				return this._parent;
			}
			set
			{
				if ((this._parent != value))
				{
					this._parent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idmadv", DbType="VarChar(50)")]
		public string idmadv
		{
			get
			{
				return this._idmadv;
			}
			set
			{
				if ((this._idmadv != value))
				{
					this._idmadv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madv", DbType="VarChar(50)")]
		public string madv
		{
			get
			{
				return this._madv;
			}
			set
			{
				if ((this._madv != value))
				{
					this._madv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idmacs", DbType="VarChar(50)")]
		public string idmacs
		{
			get
			{
				return this._idmacs;
			}
			set
			{
				if ((this._idmacs != value))
				{
					this._idmacs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabp", DbType="VarChar(50)")]
		public string mabp
		{
			get
			{
				return this._mabp;
			}
			set
			{
				if ((this._mabp != value))
				{
					this._mabp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donvidathang", DbType="VarChar(50)")]
		public string donvidathang
		{
			get
			{
				return this._donvidathang;
			}
			set
			{
				if ((this._donvidathang != value))
				{
					this._donvidathang = value;
				}
			}
		}
	}
	
	public partial class sp_mapping_Donvidathang_Department_byidmacsResult
	{
		
		private string _internalid;
		
		private string _externalid;
		
		private string _name;
		
		private string _parent;
		
		private string _idmadv;
		
		private string _madv;
		
		private string _idmacs;
		
		private string _mabp;
		
		private string _donvidathang;
		
		public sp_mapping_Donvidathang_Department_byidmacsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_internalid", DbType="VarChar(50)")]
		public string internalid
		{
			get
			{
				return this._internalid;
			}
			set
			{
				if ((this._internalid != value))
				{
					this._internalid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externalid", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string externalid
		{
			get
			{
				return this._externalid;
			}
			set
			{
				if ((this._externalid != value))
				{
					this._externalid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent", DbType="VarChar(50)")]
		public string parent
		{
			get
			{
				return this._parent;
			}
			set
			{
				if ((this._parent != value))
				{
					this._parent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idmadv", DbType="VarChar(50)")]
		public string idmadv
		{
			get
			{
				return this._idmadv;
			}
			set
			{
				if ((this._idmadv != value))
				{
					this._idmadv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madv", DbType="VarChar(50)")]
		public string madv
		{
			get
			{
				return this._madv;
			}
			set
			{
				if ((this._madv != value))
				{
					this._madv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idmacs", DbType="VarChar(50)")]
		public string idmacs
		{
			get
			{
				return this._idmacs;
			}
			set
			{
				if ((this._idmacs != value))
				{
					this._idmacs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabp", DbType="VarChar(50)")]
		public string mabp
		{
			get
			{
				return this._mabp;
			}
			set
			{
				if ((this._mabp != value))
				{
					this._mabp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donvidathang", DbType="VarChar(50)")]
		public string donvidathang
		{
			get
			{
				return this._donvidathang;
			}
			set
			{
				if ((this._donvidathang != value))
				{
					this._donvidathang = value;
				}
			}
		}
	}
	
	public partial class sp_mapping_NetsuiteTT_TenHopQuiResult
	{
		
		private string _Externalid;
		
		private string _Name;
		
		private string _Loai;
		
		private string _nhomsp;
		
		private string _kytudau;
		
		public sp_mapping_NetsuiteTT_TenHopQuiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Externalid", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Externalid
		{
			get
			{
				return this._Externalid;
			}
			set
			{
				if ((this._Externalid != value))
				{
					this._Externalid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this._Loai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhomsp", DbType="VarChar(10)")]
		public string nhomsp
		{
			get
			{
				return this._nhomsp;
			}
			set
			{
				if ((this._nhomsp != value))
				{
					this._nhomsp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kytudau", DbType="VarChar(1)")]
		public string kytudau
		{
			get
			{
				return this._kytudau;
			}
			set
			{
				if ((this._kytudau != value))
				{
					this._kytudau = value;
				}
			}
		}
	}
	
	public partial class api_erp_daymahang_SPMResult
	{
		
		private string _MAMH;
		
		private string _NETSUITE_THUOCTINHMAHANG;
		
		private string _MAHANG_LAYGIA;
		
		private string _DonViTinh;
		
		private string _Maloaisp;
		
		private string _Kieusp;
		
		private string _Nguongocsp;
		
		private string _TenVai;
		
		private string _SIZE;
		
		private string _TENLOAISP;
		
		private string _Donvidathang;
		
		private string _MAU;
		
		private string _Nhanhang;
		
		private string _Nhamaysx;
		
		private string _COGSACCOUNT;
		
		private string _ASSETACCOUNT;
		
		private string _INCOMEACCOUNT;
		
		private System.Nullable<System.DateTime> _NGAYNHAP;
		
		private System.Nullable<bool> _HIEULUC;
		
		private string _LOAISP;
		
		private string _TENHOPQUI;
		
		private string _GUIAPI;
		
		private System.DateTime _NgayGuiAPIHD;
		
		private string _manvmodify;
		
		private System.DateTime _ngaymodify;
		
		public api_erp_daymahang_SPMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMH", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MAMH
		{
			get
			{
				return this._MAMH;
			}
			set
			{
				if ((this._MAMH != value))
				{
					this._MAMH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NETSUITE_THUOCTINHMAHANG", DbType="VarChar(22)")]
		public string NETSUITE_THUOCTINHMAHANG
		{
			get
			{
				return this._NETSUITE_THUOCTINHMAHANG;
			}
			set
			{
				if ((this._NETSUITE_THUOCTINHMAHANG != value))
				{
					this._NETSUITE_THUOCTINHMAHANG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHANG_LAYGIA", DbType="VarChar(22)")]
		public string MAHANG_LAYGIA
		{
			get
			{
				return this._MAHANG_LAYGIA;
			}
			set
			{
				if ((this._MAHANG_LAYGIA != value))
				{
					this._MAHANG_LAYGIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this._DonViTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloaisp", DbType="VarChar(2)")]
		public string Maloaisp
		{
			get
			{
				return this._Maloaisp;
			}
			set
			{
				if ((this._Maloaisp != value))
				{
					this._Maloaisp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kieusp", DbType="VarChar(4)")]
		public string Kieusp
		{
			get
			{
				return this._Kieusp;
			}
			set
			{
				if ((this._Kieusp != value))
				{
					this._Kieusp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nguongocsp", DbType="VarChar(1)")]
		public string Nguongocsp
		{
			get
			{
				return this._Nguongocsp;
			}
			set
			{
				if ((this._Nguongocsp != value))
				{
					this._Nguongocsp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVai", DbType="VarChar(3)")]
		public string TenVai
		{
			get
			{
				return this._TenVai;
			}
			set
			{
				if ((this._TenVai != value))
				{
					this._TenVai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIZE", DbType="VarChar(4)")]
		public string SIZE
		{
			get
			{
				return this._SIZE;
			}
			set
			{
				if ((this._SIZE != value))
				{
					this._SIZE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAISP", DbType="NVarChar(200)")]
		public string TENLOAISP
		{
			get
			{
				return this._TENLOAISP;
			}
			set
			{
				if ((this._TENLOAISP != value))
				{
					this._TENLOAISP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Donvidathang", DbType="VarChar(3)")]
		public string Donvidathang
		{
			get
			{
				return this._Donvidathang;
			}
			set
			{
				if ((this._Donvidathang != value))
				{
					this._Donvidathang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAU", DbType="VarChar(3)")]
		public string MAU
		{
			get
			{
				return this._MAU;
			}
			set
			{
				if ((this._MAU != value))
				{
					this._MAU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhanhang", DbType="VarChar(5)")]
		public string Nhanhang
		{
			get
			{
				return this._Nhanhang;
			}
			set
			{
				if ((this._Nhanhang != value))
				{
					this._Nhanhang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhamaysx", DbType="VarChar(1)")]
		public string Nhamaysx
		{
			get
			{
				return this._Nhamaysx;
			}
			set
			{
				if ((this._Nhamaysx != value))
				{
					this._Nhamaysx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COGSACCOUNT", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string COGSACCOUNT
		{
			get
			{
				return this._COGSACCOUNT;
			}
			set
			{
				if ((this._COGSACCOUNT != value))
				{
					this._COGSACCOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASSETACCOUNT", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string ASSETACCOUNT
		{
			get
			{
				return this._ASSETACCOUNT;
			}
			set
			{
				if ((this._ASSETACCOUNT != value))
				{
					this._ASSETACCOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INCOMEACCOUNT", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string INCOMEACCOUNT
		{
			get
			{
				return this._INCOMEACCOUNT;
			}
			set
			{
				if ((this._INCOMEACCOUNT != value))
				{
					this._INCOMEACCOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNHAP", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYNHAP
		{
			get
			{
				return this._NGAYNHAP;
			}
			set
			{
				if ((this._NGAYNHAP != value))
				{
					this._NGAYNHAP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIEULUC", DbType="Bit")]
		public System.Nullable<bool> HIEULUC
		{
			get
			{
				return this._HIEULUC;
			}
			set
			{
				if ((this._HIEULUC != value))
				{
					this._HIEULUC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAISP", DbType="VarChar(14)")]
		public string LOAISP
		{
			get
			{
				return this._LOAISP;
			}
			set
			{
				if ((this._LOAISP != value))
				{
					this._LOAISP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHOPQUI", DbType="NVarChar(MAX)")]
		public string TENHOPQUI
		{
			get
			{
				return this._TENHOPQUI;
			}
			set
			{
				if ((this._TENHOPQUI != value))
				{
					this._TENHOPQUI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUIAPI", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string GUIAPI
		{
			get
			{
				return this._GUIAPI;
			}
			set
			{
				if ((this._GUIAPI != value))
				{
					this._GUIAPI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGuiAPIHD", DbType="DateTime NOT NULL")]
		public System.DateTime NgayGuiAPIHD
		{
			get
			{
				return this._NgayGuiAPIHD;
			}
			set
			{
				if ((this._NgayGuiAPIHD != value))
				{
					this._NgayGuiAPIHD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manvmodify", DbType="VarChar(50)")]
		public string manvmodify
		{
			get
			{
				return this._manvmodify;
			}
			set
			{
				if ((this._manvmodify != value))
				{
					this._manvmodify = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaymodify", DbType="DateTime NOT NULL")]
		public System.DateTime ngaymodify
		{
			get
			{
				return this._ngaymodify;
			}
			set
			{
				if ((this._ngaymodify != value))
				{
					this._ngaymodify = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
