//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSendCapNhapDH.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.2.182;Initial Catalog=QLDonHang09;Persist Security Info=True;" +
            "User ID=sa")]
        public string QLDonHang09ConnectionString {
            get {
                return ((string)(this["QLDonHang09ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.2.182;Initial Catalog=NotificationManagement;Persist Security" +
            " Info=True;User ID=sa;Password=9905376")]
        public string NotificationManagementConnectionString {
            get {
                return ((string)(this["NotificationManagementConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.2.182;Initial Catalog=QUANLYKHOMOC;Persist Security Info=True" +
            ";User ID=sa;Password=9905376")]
        public string QUANLYKHOMOCConnectionString {
            get {
                return ((string)(this["QUANLYKHOMOCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.2.182;Initial Catalog=QLSANPHAMMAY2023;Persist Security Info=" +
            "True;User ID=sa")]
        public string QLSANPHAMMAY2023ConnectionString {
            get {
                return ((string)(this["QLSANPHAMMAY2023ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.2.182;Initial Catalog=NetsuiteTT;Persist Security Info=True;U" +
            "ser ID=sa")]
        public string NetsuiteTTConnectionString {
            get {
                return ((string)(this["NetsuiteTTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.netsuite.com/services/NetSuitePort_2023_2")]
        public string AutoSendCapNhapDH_com_netsuite_webservices_NetSuiteService {
            get {
                return ((string)(this["AutoSendCapNhapDH_com_netsuite_webservices_NetSuiteService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.2.182;Initial Catalog=QLSANPHAMMAY2023;Persist Security Info=" +
            "True;User ID=sa;Password=9905376")]
        public string QLSANPHAMMAY2023ConnectionString1 {
            get {
                return ((string)(this["QLSANPHAMMAY2023ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.2.182;Initial Catalog=NetsuiteTT;Persist Security Info=True;U" +
            "ser ID=sa;Password=9905376")]
        public string NetsuiteTTConnectionString1 {
            get {
                return ((string)(this["NetsuiteTTConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.2.182;Initial Catalog=QuanLyKhoMoc2023;User ID=sa;Password=99" +
            "05376")]
        public string QuanLyKhoMoc2023ConnectionString {
            get {
                return ((string)(this["QuanLyKhoMoc2023ConnectionString"]));
            }
        }
    }
}
