#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSendCapNhapDH.QUANLYKHOMOC2023
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyKhoMoc2023")]
	public partial class QLKhoMoc2023DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertdmNhomMay(dmNhomMay instance);
    partial void UpdatedmNhomMay(dmNhomMay instance);
    partial void DeletedmNhomMay(dmNhomMay instance);
    #endregion
		
		public QLKhoMoc2023DataContext() : 
				base(global::AutoSendCapNhapDH.Properties.Settings.Default.QuanLyKhoMoc2023ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLKhoMoc2023DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKhoMoc2023DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKhoMoc2023DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKhoMoc2023DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dmNhomMay> dmNhomMays
		{
			get
			{
				return this.GetTable<dmNhomMay>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_API_Load_By_MH")]
		public ISingleResult<Sp_API_Load_By_MHResult> Sp_API_Load_By_MH([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mahang", DbType="VarChar(50)")] string mahang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahang);
			return ((ISingleResult<Sp_API_Load_By_MHResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_Update_GuiAPI_MahangMOC")]
		public int Sp_Update_GuiAPI_MahangMOC([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string mahangmoc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahangmoc);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dmNhomMay")]
	public partial class dmNhomMay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Manhamay;
		
		private string _Nhommay;
		
		private string _Tennhommay;
		
		private string _Donvitinh;
		
		private string _Ghichu;
		
		private System.Nullable<bool> _Hieuluc;
		
		private string _Kieudet;
		
		private string _Manvcn;
		
		private System.Nullable<System.DateTime> _Ngaycn;
		
		private string _Manvmodify;
		
		private System.Nullable<System.DateTime> _Ngaymodify;
		
		private System.Guid _ID_nhommay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnManhamayChanging(string value);
    partial void OnManhamayChanged();
    partial void OnNhommayChanging(string value);
    partial void OnNhommayChanged();
    partial void OnTennhommayChanging(string value);
    partial void OnTennhommayChanged();
    partial void OnDonvitinhChanging(string value);
    partial void OnDonvitinhChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    partial void OnHieulucChanging(System.Nullable<bool> value);
    partial void OnHieulucChanged();
    partial void OnKieudetChanging(string value);
    partial void OnKieudetChanged();
    partial void OnManvcnChanging(string value);
    partial void OnManvcnChanged();
    partial void OnNgaycnChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaycnChanged();
    partial void OnManvmodifyChanging(string value);
    partial void OnManvmodifyChanged();
    partial void OnNgaymodifyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaymodifyChanged();
    partial void OnID_nhommayChanging(System.Guid value);
    partial void OnID_nhommayChanged();
    #endregion
		
		public dmNhomMay()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhamay", DbType="VarChar(50)")]
		public string Manhamay
		{
			get
			{
				return this._Manhamay;
			}
			set
			{
				if ((this._Manhamay != value))
				{
					this.OnManhamayChanging(value);
					this.SendPropertyChanging();
					this._Manhamay = value;
					this.SendPropertyChanged("Manhamay");
					this.OnManhamayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhommay", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Nhommay
		{
			get
			{
				return this._Nhommay;
			}
			set
			{
				if ((this._Nhommay != value))
				{
					this.OnNhommayChanging(value);
					this.SendPropertyChanging();
					this._Nhommay = value;
					this.SendPropertyChanged("Nhommay");
					this.OnNhommayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tennhommay", DbType="NVarChar(200)")]
		public string Tennhommay
		{
			get
			{
				return this._Tennhommay;
			}
			set
			{
				if ((this._Tennhommay != value))
				{
					this.OnTennhommayChanging(value);
					this.SendPropertyChanging();
					this._Tennhommay = value;
					this.SendPropertyChanged("Tennhommay");
					this.OnTennhommayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Donvitinh", DbType="VarChar(50)")]
		public string Donvitinh
		{
			get
			{
				return this._Donvitinh;
			}
			set
			{
				if ((this._Donvitinh != value))
				{
					this.OnDonvitinhChanging(value);
					this.SendPropertyChanging();
					this._Donvitinh = value;
					this.SendPropertyChanged("Donvitinh");
					this.OnDonvitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NVarChar(MAX)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this.OnGhichuChanging(value);
					this.SendPropertyChanging();
					this._Ghichu = value;
					this.SendPropertyChanged("Ghichu");
					this.OnGhichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hieuluc", DbType="Bit")]
		public System.Nullable<bool> Hieuluc
		{
			get
			{
				return this._Hieuluc;
			}
			set
			{
				if ((this._Hieuluc != value))
				{
					this.OnHieulucChanging(value);
					this.SendPropertyChanging();
					this._Hieuluc = value;
					this.SendPropertyChanged("Hieuluc");
					this.OnHieulucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kieudet", DbType="NVarChar(200)")]
		public string Kieudet
		{
			get
			{
				return this._Kieudet;
			}
			set
			{
				if ((this._Kieudet != value))
				{
					this.OnKieudetChanging(value);
					this.SendPropertyChanging();
					this._Kieudet = value;
					this.SendPropertyChanged("Kieudet");
					this.OnKieudetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manvcn", DbType="VarChar(50)")]
		public string Manvcn
		{
			get
			{
				return this._Manvcn;
			}
			set
			{
				if ((this._Manvcn != value))
				{
					this.OnManvcnChanging(value);
					this.SendPropertyChanging();
					this._Manvcn = value;
					this.SendPropertyChanged("Manvcn");
					this.OnManvcnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaycn", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaycn
		{
			get
			{
				return this._Ngaycn;
			}
			set
			{
				if ((this._Ngaycn != value))
				{
					this.OnNgaycnChanging(value);
					this.SendPropertyChanging();
					this._Ngaycn = value;
					this.SendPropertyChanged("Ngaycn");
					this.OnNgaycnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manvmodify", DbType="VarChar(50)")]
		public string Manvmodify
		{
			get
			{
				return this._Manvmodify;
			}
			set
			{
				if ((this._Manvmodify != value))
				{
					this.OnManvmodifyChanging(value);
					this.SendPropertyChanging();
					this._Manvmodify = value;
					this.SendPropertyChanged("Manvmodify");
					this.OnManvmodifyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaymodify", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaymodify
		{
			get
			{
				return this._Ngaymodify;
			}
			set
			{
				if ((this._Ngaymodify != value))
				{
					this.OnNgaymodifyChanging(value);
					this.SendPropertyChanging();
					this._Ngaymodify = value;
					this.SendPropertyChanged("Ngaymodify");
					this.OnNgaymodifyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_nhommay", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID_nhommay
		{
			get
			{
				return this._ID_nhommay;
			}
			set
			{
				if ((this._ID_nhommay != value))
				{
					this.OnID_nhommayChanging(value);
					this.SendPropertyChanging();
					this._ID_nhommay = value;
					this.SendPropertyChanged("ID_nhommay");
					this.OnID_nhommayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class Sp_API_Load_By_MHResult
	{
		
		private string _Mahang;
		
		private string _PvBanhang;
		
		private string _Madh;
		
		private string _Bong;
		
		private string _MaHang_GC;
		
		private string _Tentm;
		
		private System.Nullable<System.DateTime> _Ngaybd;
		
		private System.Nullable<decimal> _Matdo;
		
		private System.Nullable<decimal> _Tocdo;
		
		private System.Nullable<decimal> _Khomoc;
		
		private System.Nullable<decimal> _Beam;
		
		private string _Nhomhang;
		
		private System.Nullable<decimal> _DonViGiaCong;
		
		private string _Maphien;
		
		private System.Nullable<System.DateTime> _NgayNhap;
		
		private string _Manvhieuchinh;
		
		private System.Nullable<System.DateTime> _NgayHieuChinh;
		
		private string _Manvcapnhat;
		
		private string _Nhommaydet;
		
		private System.Guid _ID_mahang;
		
		private string _Tensanpham;
		
		private string _Khovaimoc;
		
		private string _Bongnen;
		
		private string _Loaimaydet;
		
		private string _Congnghedet;
		
		private System.Nullable<bool> _GUIAPI;
		
		private System.Nullable<System.DateTime> _NgayGuiAPIHD;
		
		public Sp_API_Load_By_MHResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahang", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Mahang
		{
			get
			{
				return this._Mahang;
			}
			set
			{
				if ((this._Mahang != value))
				{
					this._Mahang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PvBanhang", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string PvBanhang
		{
			get
			{
				return this._PvBanhang;
			}
			set
			{
				if ((this._PvBanhang != value))
				{
					this._PvBanhang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madh", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Madh
		{
			get
			{
				return this._Madh;
			}
			set
			{
				if ((this._Madh != value))
				{
					this._Madh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bong", DbType="VarChar(50)")]
		public string Bong
		{
			get
			{
				return this._Bong;
			}
			set
			{
				if ((this._Bong != value))
				{
					this._Bong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHang_GC", DbType="VarChar(50)")]
		public string MaHang_GC
		{
			get
			{
				return this._MaHang_GC;
			}
			set
			{
				if ((this._MaHang_GC != value))
				{
					this._MaHang_GC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tentm", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Tentm
		{
			get
			{
				return this._Tentm;
			}
			set
			{
				if ((this._Tentm != value))
				{
					this._Tentm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaybd", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaybd
		{
			get
			{
				return this._Ngaybd;
			}
			set
			{
				if ((this._Ngaybd != value))
				{
					this._Ngaybd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matdo", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Matdo
		{
			get
			{
				return this._Matdo;
			}
			set
			{
				if ((this._Matdo != value))
				{
					this._Matdo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tocdo", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Tocdo
		{
			get
			{
				return this._Tocdo;
			}
			set
			{
				if ((this._Tocdo != value))
				{
					this._Tocdo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khomoc", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Khomoc
		{
			get
			{
				return this._Khomoc;
			}
			set
			{
				if ((this._Khomoc != value))
				{
					this._Khomoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beam", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Beam
		{
			get
			{
				return this._Beam;
			}
			set
			{
				if ((this._Beam != value))
				{
					this._Beam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhomhang", DbType="NVarChar(50)")]
		public string Nhomhang
		{
			get
			{
				return this._Nhomhang;
			}
			set
			{
				if ((this._Nhomhang != value))
				{
					this._Nhomhang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViGiaCong", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DonViGiaCong
		{
			get
			{
				return this._DonViGiaCong;
			}
			set
			{
				if ((this._DonViGiaCong != value))
				{
					this._DonViGiaCong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphien", DbType="VarChar(50)")]
		public string Maphien
		{
			get
			{
				return this._Maphien;
			}
			set
			{
				if ((this._Maphien != value))
				{
					this._Maphien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this._NgayNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manvhieuchinh", DbType="VarChar(50)")]
		public string Manvhieuchinh
		{
			get
			{
				return this._Manvhieuchinh;
			}
			set
			{
				if ((this._Manvhieuchinh != value))
				{
					this._Manvhieuchinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHieuChinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHieuChinh
		{
			get
			{
				return this._NgayHieuChinh;
			}
			set
			{
				if ((this._NgayHieuChinh != value))
				{
					this._NgayHieuChinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manvcapnhat", DbType="VarChar(50)")]
		public string Manvcapnhat
		{
			get
			{
				return this._Manvcapnhat;
			}
			set
			{
				if ((this._Manvcapnhat != value))
				{
					this._Manvcapnhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhommaydet", DbType="VarChar(50)")]
		public string Nhommaydet
		{
			get
			{
				return this._Nhommaydet;
			}
			set
			{
				if ((this._Nhommaydet != value))
				{
					this._Nhommaydet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_mahang", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ID_mahang
		{
			get
			{
				return this._ID_mahang;
			}
			set
			{
				if ((this._ID_mahang != value))
				{
					this._ID_mahang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tensanpham", DbType="VarChar(3)")]
		public string Tensanpham
		{
			get
			{
				return this._Tensanpham;
			}
			set
			{
				if ((this._Tensanpham != value))
				{
					this._Tensanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khovaimoc", DbType="VarChar(1)")]
		public string Khovaimoc
		{
			get
			{
				return this._Khovaimoc;
			}
			set
			{
				if ((this._Khovaimoc != value))
				{
					this._Khovaimoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bongnen", DbType="VarChar(5)")]
		public string Bongnen
		{
			get
			{
				return this._Bongnen;
			}
			set
			{
				if ((this._Bongnen != value))
				{
					this._Bongnen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loaimaydet", DbType="VarChar(1)")]
		public string Loaimaydet
		{
			get
			{
				return this._Loaimaydet;
			}
			set
			{
				if ((this._Loaimaydet != value))
				{
					this._Loaimaydet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Congnghedet", DbType="VarChar(10)")]
		public string Congnghedet
		{
			get
			{
				return this._Congnghedet;
			}
			set
			{
				if ((this._Congnghedet != value))
				{
					this._Congnghedet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUIAPI", DbType="Bit")]
		public System.Nullable<bool> GUIAPI
		{
			get
			{
				return this._GUIAPI;
			}
			set
			{
				if ((this._GUIAPI != value))
				{
					this._GUIAPI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGuiAPIHD", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGuiAPIHD
		{
			get
			{
				return this._NgayGuiAPIHD;
			}
			set
			{
				if ((this._NgayGuiAPIHD != value))
				{
					this._NgayGuiAPIHD = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
